glossia_fenics:
    image: gosmart/glossia-fenics
    command: --interpreter "python3 /mesh_and_go.py --mesh /shared/input/elmer_libnuma.msh:/shared/input/mesh_labelling.yml" --target run_ire.py --static --passthrough --archive /shared/code
    volumes:
        - ./code:/shared/code
        - ./gssfhome:/var/run/gssf
        - ./input:/shared/input
        - ./output:/shared/output
